version: 2.1

job-defaults: &job-defaults
  docker:
    - image: circleci/node:14

commands:
  seed_npmrc:
    description: Uses $NPM_TOKEN to authenticate to registry.npmjs.org
    steps:
      - run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
node-modules-cache-key: &node-modules-cache-key
  key: node-modules-{{ arch }}-{{ .Environment.CACHE_VERSION }}-{{ checksum "~/project/package-lock.json" }}

npm-packages-cache-key: &npm-packages-cache-key # no arch needed because the packages are platform agnostic
  key: npm-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "~/project/package-lock.json" }}

jobs:
  initialize-workspace:
    <<: *job-defaults
    steps:
      - checkout
      - seed_npmrc
      - restore_cache:
          <<: *node-modules-cache-key
      - run: |
          if ! [[ -d ~/project/node_modules/ ]]; then
            npm ci --prefer-offline --no-audit
          fi
      - save_cache:
          <<: *node-modules-cache-key
          paths:
            - ~/project/node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  lint:
    <<: *job-defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run lint

  test-with-coverage:
    <<: *job-defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run test:coverage
      - store_artifacts:
          path: coverage/

  publish:
    <<: *job-defaults
    steps:
      - attach_workspace:
          at: ~/project
      - seed_npmrc
      - run: npm publish
      - store_artifacts:
          path: dist/

filter-ignore-master: &filter-ignore-master
  filters:
    branches:
      ignore: master
    tags:
      only: /^v.*/

workflows:
  version: 2

  build:
    jobs:
      - initialize-workspace:
          <<: *filter-ignore-master
          context: development

      - lint:
          <<: *filter-ignore-master
          requires:
            - initialize-workspace

      - test-with-coverage:
          <<: *filter-ignore-master
          requires:
            - initialize-workspace

      - publish:
          context: npmjs.com/org/parrable
          requires:
            - lint
            - test-with-coverage
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
